USE [master]

/****** Object:  Database [BLSInventory]    Script Date: 9/30/2015 9:29:18 AM ******/
CREATE DATABASE [BLSInventory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BLSInventory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BLSInventory.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BLSInventory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BLSInventory_log.ldf' , SIZE = 1600KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

ALTER DATABASE [BLSInventory] SET COMPATIBILITY_LEVEL = 110

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BLSInventory].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [BLSInventory] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [BLSInventory] SET ANSI_NULLS OFF 

ALTER DATABASE [BLSInventory] SET ANSI_PADDING OFF 

ALTER DATABASE [BLSInventory] SET ANSI_WARNINGS OFF 

ALTER DATABASE [BLSInventory] SET ARITHABORT OFF 

ALTER DATABASE [BLSInventory] SET AUTO_CLOSE OFF 

ALTER DATABASE [BLSInventory] SET AUTO_CREATE_STATISTICS ON 

ALTER DATABASE [BLSInventory] SET AUTO_SHRINK OFF 

ALTER DATABASE [BLSInventory] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [BLSInventory] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [BLSInventory] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [BLSInventory] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [BLSInventory] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [BLSInventory] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [BLSInventory] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [BLSInventory] SET  ENABLE_BROKER 

ALTER DATABASE [BLSInventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [BLSInventory] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [BLSInventory] SET TRUSTWORTHY OFF 

ALTER DATABASE [BLSInventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [BLSInventory] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [BLSInventory] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [BLSInventory] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [BLSInventory] SET RECOVERY FULL 

ALTER DATABASE [BLSInventory] SET  MULTI_USER 

ALTER DATABASE [BLSInventory] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [BLSInventory] SET DB_CHAINING OFF 

ALTER DATABASE [BLSInventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [BLSInventory] SET TARGET_RECOVERY_TIME = 0 SECONDS 
