USE [master]

/****** Object:  Database [ABCInventory]    Script Date: 9/30/2015 9:29:18 AM ******/
CREATE DATABASE [ABCInventory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ABCInventory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ABCInventory.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ABCInventory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\ABCInventory_log.ldf' , SIZE = 1600KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

ALTER DATABASE [ABCInventory] SET COMPATIBILITY_LEVEL = 110

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ABCInventory].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [ABCInventory] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [ABCInventory] SET ANSI_NULLS OFF 

ALTER DATABASE [ABCInventory] SET ANSI_PADDING OFF 

ALTER DATABASE [ABCInventory] SET ANSI_WARNINGS OFF 

ALTER DATABASE [ABCInventory] SET ARITHABORT OFF 

ALTER DATABASE [ABCInventory] SET AUTO_CLOSE OFF 

ALTER DATABASE [ABCInventory] SET AUTO_CREATE_STATISTICS ON 

ALTER DATABASE [ABCInventory] SET AUTO_SHRINK OFF 

ALTER DATABASE [ABCInventory] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [ABCInventory] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [ABCInventory] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [ABCInventory] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [ABCInventory] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [ABCInventory] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [ABCInventory] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [ABCInventory] SET  ENABLE_BROKER 

ALTER DATABASE [ABCInventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [ABCInventory] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [ABCInventory] SET TRUSTWORTHY OFF 

ALTER DATABASE [ABCInventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [ABCInventory] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [ABCInventory] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [ABCInventory] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [ABCInventory] SET RECOVERY FULL 

ALTER DATABASE [ABCInventory] SET  MULTI_USER 

ALTER DATABASE [ABCInventory] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [ABCInventory] SET DB_CHAINING OFF 

ALTER DATABASE [ABCInventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [ABCInventory] SET TARGET_RECOVERY_TIME = 0 SECONDS 